export default {
    products: [{
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '../images/slimshirt.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 11,
    },
    {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '../images/slimshirt.jpg',
        price: 50,
        brand: 'Nikeee',
        rating: 4.2,
        numReviews: 10,
    },
    {
        _id: '3',
        name: 'Best Pants',
        category: 'Pants',
        image: '../images/slimshirt.jpg',
        price: 70,
        brand: 'Nikew',
        rating: 4.3,
        numReviews: 11,
    },
    {
        _id: '4',
        name: 'Best Pants',
        category: 'Pants',
        image: '../images/slimshirt.jpg',
        price: 90,
        brand: 'Nikee',
        rating: 4.7,
        numReviews: 13,
    },
    ]
}
